# Generated by Django 5.0.1 on 2024-03-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Created_date',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='customer',
            name='post_code',
            field=models.CharField(default='', max_length=12),
        ),
    ]
